"""Create the initial Labore Portal relational schema."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def uuid_column(**kwargs):
    return sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), **kwargs)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table("users", uuid_column(primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("display_name", sa.String(160), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("failed_login_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("locked_until", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("companies", uuid_column(primary_key=True), sa.Column("legal_name", sa.String(240), nullable=False), sa.Column("trade_name", sa.String(240)), sa.Column("tax_identifier", sa.String(32), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("roles", uuid_column(primary_key=True), sa.Column("name", sa.String(80), nullable=False, unique=True), sa.Column("description", sa.String(255)))
    op.create_table("permissions", uuid_column(primary_key=True), sa.Column("resource", sa.String(80), nullable=False), sa.Column("action", sa.String(40), nullable=False), sa.UniqueConstraint("resource", "action", name="uq_permissions_resource_action"))
    op.create_table("departments", uuid_column(primary_key=True), sa.Column("name", sa.String(100), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("document_categories", uuid_column(primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("name", sa.String(160), nullable=False))
    op.create_table("company_users", sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("role_permissions", sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True), sa.Column("permission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("permissions.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("user_roles", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("competencies", uuid_column(primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("year", sa.Integer(), nullable=False), sa.Column("month", sa.Integer(), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="incomplete"), sa.UniqueConstraint("company_id", "year", "month", name="uq_competency_company_period"))
    op.create_table("competency_requirements", uuid_column(primary_key=True), sa.Column("competency_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("competencies.id", ondelete="CASCADE"), nullable=False), sa.Column("requirement_key", sa.String(100), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="pending"), sa.Column("is_required", sa.Boolean(), nullable=False, server_default=sa.true()), sa.UniqueConstraint("competency_id", "requirement_key", name="uq_requirement_key"))
    op.create_table("bank_accounts", uuid_column(primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("institution_name", sa.String(160), nullable=False), sa.Column("masked_identifier", sa.String(80), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("company_id", "masked_identifier", name="uq_bank_company_identifier"))
    op.create_table("documents", uuid_column(primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="RESTRICT"), nullable=False), sa.Column("competency_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("competencies.id", ondelete="SET NULL")), sa.Column("category_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("document_categories.id", ondelete="RESTRICT"), nullable=False), sa.Column("original_filename", sa.String(255), nullable=False), sa.Column("normalized_filename", sa.String(255), nullable=False), sa.Column("logical_path", sa.String(1024), nullable=False, unique=True), sa.Column("checksum_hash", sa.String(128), nullable=False), sa.Column("file_size_bytes", sa.Integer(), nullable=False), sa.Column("mime_type", sa.String(160), nullable=False), sa.Column("uploaded_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="quarantined"), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_documents_company_competency", "documents", ["company_id", "competency_id"])
    op.create_index("ix_documents_status", "documents", ["status"])
    op.create_table("accounting_movements", uuid_column(primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("competency_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("competencies.id", ondelete="CASCADE"), nullable=False), sa.Column("note", sa.Text()), sa.Column("status", sa.String(30), nullable=False, server_default="incomplete"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("movement_documents", sa.Column("movement_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("accounting_movements.id", ondelete="CASCADE"), primary_key=True), sa.Column("document_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="RESTRICT"), primary_key=True), sa.Column("document_type", sa.String(30), nullable=False))
    op.create_table("tickets", uuid_column(primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("requester_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("department_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("departments.id", ondelete="SET NULL")), sa.Column("subject", sa.String(240), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="open"), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("ticket_participants", sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("ticket_messages", uuid_column(primary_key=True), sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="CASCADE"), nullable=False), sa.Column("author_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_ticket_messages_ticket_id", "ticket_messages", ["ticket_id"])
    op.create_table("ticket_attachments", sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="CASCADE"), primary_key=True), sa.Column("document_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="RESTRICT"), primary_key=True))
    op.create_table("notifications", uuid_column(primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_table("audit_logs", uuid_column(primary_key=True), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="SET NULL")), sa.Column("action", sa.String(80), nullable=False), sa.Column("target_type", sa.String(80), nullable=False), sa.Column("target_id", postgresql.UUID(as_uuid=True)), sa.Column("outcome", sa.String(30), nullable=False), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_audit_logs_company_created", "audit_logs", ["company_id", "created_at"])
    op.create_table("sessions", uuid_column(primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(128), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])


def downgrade() -> None:
    for table in ["sessions", "audit_logs", "notifications", "ticket_attachments", "ticket_messages", "ticket_participants", "tickets", "movement_documents", "accounting_movements", "documents", "bank_accounts", "competency_requirements", "competencies", "user_roles", "role_permissions", "company_users", "document_categories", "departments", "permissions", "roles", "companies", "users"]:
        op.drop_table(table)
